LicoBundle\Entity\Licorne:
    type: entity
    table: null
    repositoryClass: LicoBundle\Repository\LicorneRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        iDLicorne:
            type: integer
            unique: true
            column: ID_Licorne
        nomLicorne:
            type: string
            length: 255
            unique: true
            column: Nom_Licorne
        corneLicorne:
            type: string
            length: 255
            unique: false
            column: Corne_Licorne
        yeuxLicorne:
            type: string
            length: 255
            unique: false
            column: Yeux_Licorne
        alignementLicorne:
            type: string
            length: 255
            unique: false
            column: Alignement_Licorne
        regimeLicorne:
            type: string
            length: 255
            unique: false
            column: Regime_Licorne
        pelageLicorne:
            type: string
            length: 255
            unique: false
            column: Pelage_Licorne
        imageLicorne:
            type: string
            length: 255
            unique: false
            column: Image_Licorne
    lifecycleCallbacks: {  }
    oneToOne:
        Environnement:
            targetEntity: Environnement
            joinColumn:
                name: environnement_id
                referencedColumnName: id
