<?php

namespace LicoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EnvironnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnvironnementRepository extends EntityRepository
{
}
