<?php

namespace LicoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LicorneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicorneRepository extends EntityRepository
{
}
